obj :=	idt.o			\
	intr.o			\
	excp.o			\
	device.o		\
	mmu_walk.o		\
	npt_walk.o		\
	db.o			\
	cpuid.o			\
	cr.o			\
	dr.o			\
	insn.o			\
	msr.o			\
	disasm.o		\
	emulate.o		\
	emulate_insn.o		\
	emulate_rmode.o		\
	emulate_int.o		\
	emulate_int15.o		\
	pvl.o			\
	vm.o			\
#	smi.o			\
