obj :=  vmx_exit.o			\
	vmx_exit_fail.o			\
	vmx_exit_gp.o			\
	vmx_exit_pf.o			\
	vmx_exit_cr.o			\
	vmx_exit_dr.o			\
	vmx_exit_dt.o			\
	vmx_exit_msr.o			\
	vmx_exit_cpuid.o		\
	vmx_exit_int.o			\
	vmx_exit_excp.o			\
	vmx_exit_io.o			\
	vmx_insn.o			\
	vmx_ept.o			\
	vmx_vmcs_acc.o

